import DesignExamples

-- 証明依存を再現して確認する。sorryAx と実行結果を信頼する追加公理を使わない。
#print axioms DesignExamples.Ramsey.ramsey_six
#print axioms DesignExamples.Ramsey.ramsey_five_counterexample
#print axioms DesignExamples.Schur.schur_two
#print axioms DesignExamples.Schur.schur_four_counterexample
#print axioms DesignExamples.Pumping.run_repeats_state
#print axioms DesignExamples.Pumping.split_to_loop
#print axioms DesignExamples.Pumping.pumping_lemma
#print axioms DesignExamples.Hall.hall_iff_matching
#print axioms DesignExamples.Hall.pattern_hall
#print axioms DesignExamples.Involution.involution_card_even
#print axioms DesignExamples.Involution.involution_sum_zero
#print axioms DesignExamples.Involution.alternating_powerset_sum
#print axioms DesignExamples.GroupWords.exists_reduced
#print axioms DesignExamples.Permutations.finite_permutation_factors
#print axioms DesignExamples.WalkPaths.walk_to_path
#print axioms DesignExamples.Pigeonhole.collision
#print axioms DesignExamples.ErdosSzekeres.erdos_szekeres_five
#print axioms DesignExamples.ErdosSzekeres.erdos_szekeres_prefix
#print axioms DesignExamples.PatternStyle.Ramsey.ramsey_six
#print axioms DesignExamples.PatternStyle.Ramsey.ramsey_five_counterexample
#print axioms DesignExamples.PatternStyle.Schur.schur_two
#print axioms DesignExamples.PatternStyle.Schur.schur_four_counterexample
#print axioms DesignExamples.PatternStyle.Pumping.run_repeats_state
#print axioms DesignExamples.PatternStyle.Pumping.split_to_loop
#print axioms DesignExamples.PatternStyle.Pumping.pumping_lemma
#print axioms DesignExamples.PatternStyle.Hall.hall_iff_matching
#print axioms DesignExamples.PatternStyle.Hall.pattern_hall
#print axioms DesignExamples.PatternStyle.Involution.involution_card_even
#print axioms DesignExamples.PatternStyle.Involution.involution_sum_zero
#print axioms DesignExamples.PatternStyle.Involution.alternating_powerset_sum
#print axioms DesignExamples.PatternStyle.GroupWords.exists_reduced
#print axioms DesignExamples.PatternStyle.Permutations.finite_permutation_factors
#print axioms DesignExamples.PatternStyle.WalkPaths.walk_to_path
#print axioms DesignExamples.PatternStyle.Pigeonhole.collision
#print axioms DesignExamples.PatternStyle.ErdosSzekeres.erdos_szekeres_five
#print axioms DesignExamples.PatternStyle.ErdosSzekeres.erdos_szekeres_prefix
#print axioms DesignExamples.ErdosSzekeres.four_counterexample
#print axioms DesignExamples.ErdosSzekeres.es_two
#print axioms DesignExamples.PatternStyle.ErdosSzekeres.four_counterexample
#print axioms DesignExamples.PatternStyle.ErdosSzekeres.es_two
#print axioms DesignExamples.Hall.hall
#print axioms DesignExamples.PatternStyle.Hall.hall
#print axioms DesignExamples.PatternStyle.Ramsey.pattern_iff_ordinary
#print axioms DesignExamples.PatternStyle.Schur.pattern_iff_ordinary
#print axioms DesignExamples.TwoBlocks.exhaustive
#print axioms DesignExamples.AdjacentCancellation.cut_patterns
#print axioms DesignExamples.AdjacentCancellation.step_length
#print axioms DesignExamples.AdjacentCancellation.local_confluence
#print axioms DesignExamples.AdjacentCancellation.local_confluence_by_intervals
#print axioms DesignExamples.AdjacentCancellation.confluence
#print axioms DesignExamples.PatternStyle.AdjacentCancellation.local_confluence
#print axioms DesignExamples.PatternStyle.AdjacentCancellation.confluence
