name = "egisonProverDesign"
version = "0.1.0"
defaultTargets = ["DesignExamples"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.31.0"

[[lean_lib]]
name = "DesignExamples"
