-- Manual expansion of each tuple pattern and its relation; not generated by a translator.
import DesignExamples.AdjacentCancellationCommon

namespace DesignExamples.PatternStyle.AdjacentCancellation

open DesignExamples.AdjacentCancellation

variable {A : Type*}

theorem local_confluence {w u v : List A} (hu : Step w u) (hv : Step w v) : Join u v := by
  obtain ⟨p, a, s, rfl, rfl⟩ := hu
  obtain ⟨q, b, t, hsource, rfl⟩ := hv
  rcases cut_patterns p a s q b t hsource with h | h | h | h | h
  · obtain ⟨pre, x, post, h⟩ := h
    simp_all only []
    exact join_self _
  · obtain ⟨pre, x, post, h⟩ := h
    simp_all only [List.append_assoc, List.cons_append, List.nil_append]
    exact join_self _
  · obtain ⟨pre, x, post, h⟩ := h
    simp_all only [List.append_assoc, List.cons_append, List.nil_append]
    exact join_self _
  · obtain ⟨pre, x, mid, y, post, h⟩ := h
    simp_all only [List.append_assoc, List.cons_append, List.nil_append]
    exact join_disjoint _ _ _ _ _
  · obtain ⟨pre, y, mid, x, post, h⟩ := h
    simp_all only [List.append_assoc, List.cons_append, List.nil_append]
    apply join_symm
    exact join_disjoint _ _ _ _ _

theorem confluence {w u v : List A}
    (hu : Relation.ReflTransGen Step w u) (hv : Relation.ReflTransGen Step w v) :
    Relation.Join (Relation.ReflTransGen Step) u v := by
  apply Relation.church_rosser (fun _ _ _ h₁ h₂ => ?_) hu hv
  obtain ⟨z, h₁z, h₂z⟩ := local_confluence h₁ h₂
  exact ⟨z, h₁z, h₂z.to_reflTransGen⟩

end DesignExamples.PatternStyle.AdjacentCancellation
